name: Run Coverage on PR
on: pull_request

jobs:
  build-and-run-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm i

      - name: Build code
        run: pnpm run build

      - name: Run tests and coverage
        run: pnpm run coverage
